/// Model for a generated photo
class GeneratedPhoto {
  final int? id;
  final String originalPath; // Path to original uploaded photo
  final String? generatedPath; // Path to AI-generated photo
  final String styleId; // ID of the style used
  final DateTime createdAt;
  final Map<String, dynamic> metadata; // Additional data (resolution, settings, etc.)
  final GenerationStatus status;

  GeneratedPhoto({
    this.id,
    required this.originalPath,
    this.generatedPath,
    required this.styleId,
    required this.createdAt,
    this.metadata = const {},
    this.status = GenerationStatus.pending,
  });

  /// Create from database map
  factory GeneratedPhoto.fromMap(Map<String, dynamic> map) {
    return GeneratedPhoto(
      id: map['id'] as int?,
      originalPath: map['original_path'] as String,
      generatedPath: map['generated_path'] as String?,
      styleId: map['style_id'] as String,
      createdAt: DateTime.parse(map['created_at'] as String),
      metadata: map['metadata'] != null
          ? Map<String, dynamic>.from(map['metadata'] as Map)
          : {},
      status: GenerationStatus.values.firstWhere(
        (e) => e.toString() == 'GenerationStatus.${map['status']}',
        orElse: () => GenerationStatus.pending,
      ),
    );
  }

  /// Convert to database map
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'original_path': originalPath,
      'generated_path': generatedPath,
      'style_id': styleId,
      'created_at': createdAt.toIso8601String(),
      'metadata': metadata,
      'status': status.toString().split('.').last,
    };
  }

  /// Create copy with updated fields
  GeneratedPhoto copyWith({
    int? id,
    String? originalPath,
    String? generatedPath,
    String? styleId,
    DateTime? createdAt,
    Map<String, dynamic>? metadata,
    GenerationStatus? status,
  }) {
    return GeneratedPhoto(
      id: id ?? this.id,
      originalPath: originalPath ?? this.originalPath,
      generatedPath: generatedPath ?? this.generatedPath,
      styleId: styleId ?? this.styleId,
      createdAt: createdAt ?? this.createdAt,
      metadata: metadata ?? this.metadata,
      status: status ?? this.status,
    );
  }

  @override
  String toString() {
    return 'GeneratedPhoto(id: $id, styleId: $styleId, status: $status, createdAt: $createdAt)';
  }
}

/// Status of photo generation
enum GenerationStatus {
  pending,    // Waiting to be generated
  processing, // Being generated by AI
  completed,  // Successfully generated
  failed,     // Generation failed
}
